### ISSUE TITLE
Support Cabal 1.22

### ISSUE THREAD

**Issue by JPMoresmau** [bennofs/dynamic-cabal#6]
It seems setup-config in Cabal 1.22 is binary now. So the function generateSource that tries to parse the LocalBuildInfo via read fails with Prelude.read: no parse. I suppose we have to use the Cabal function maybeGetPersistBuildConfig or something similar, but I don't know how to do that in Query.hs. To use TemplateHaskell we need to reference the Cabal API, which we don't want to do. Can we use pass a String there, even if it's not type safe? I don't mind doing it and testing it, but I don't know how to proceed. Thanks.

**Comment by bennofs** [comment]
Thanks for reporting. I am not using that cabal version myself right now (doesn't seemp to be packaged by my distribution right now), but I'll look into this. Using the cabal-provided function to read setup configuration seems like a got idea to me, then we don't have to replicate cabal's logic ourselves.

**Comment by JPMoresmau** [comment]
Actually, it seems like the Cabal code is only using the Binary instance of the LocalBuildInfo to read and serialize, which should simplify matter. The code should read the first line and if the version >=1.22 use  binary read, otherwise use "normal" read. I may have time to look into it, but that's not a promise!
