### ISSUE TITLE
-XOverlappingInstances is deprecated

### ISSUE THREAD

**Issue by BeeJay71** [bennofs/dynamic-cabal#8]
While compiling dynamic-cabal on Haskell Platform 2015.2.0.0 alpha 1 64bit which contains cabal-install version 1.22.0.1 and Glorious Glasgow Haskell Compilation System, version 7.10.0.20150316 I got this error response:

cabal install dynamic-cabal
Resolving dependencies...
Configuring dynamic-cabal-0.3.4...
Building dynamic-cabal-0.3.4...
Failed to install dynamic-cabal-0.3.4
Build log ( /Users/BeeJay/.cabal/logs/dynamic-cabal-0.3.4.log ):
[1 of 1] Compiling Main             ( /var/folders/7_/jgkw1c614b1b2lv21nwxn39c0000gn/T/dynamic-cabal-0.3.4-41741/dynamic-cabal-0.3.4/dist/setup/setup.hs, /var/folders/7_/jgkw1c614b1b2lv21nwxn39c0000gn/T/dynamic-cabal-0.3.4-41741/dynamic-cabal-0.3.4/dist/setup/Main.o )
Linking /var/folders/7_/jgkw1c614b1b2lv21nwxn39c0000gn/T/dynamic-cabal-0.3.4-41741/dynamic-cabal-0.3.4/dist/setup/setup ...
Configuring dynamic-cabal-0.3.4...
Building dynamic-cabal-0.3.4...
Preprocessing library dynamic-cabal-0.3.4...

src/Distribution/Client/Dynamic/Query.hs:4:14: Warning:
    -XOverlappingInstances is deprecated: instead use per-instance pragmas OVERLAPPING/OVERLAPPABLE/OVERLAPS
[1 of 4] Compiling Distribution.Client.Dynamic.Query ( src/Distribution/Client/Dynamic/Query.hs, dist/build/Distribution/Client/Dynamic/Query.o )

src/Distribution/Client/Dynamic/Query.hs:190:36:
    Couldn't match expected type ‘DynFlags.PackageFlag’
                with actual type ‘DynFlags.ModRenaming -> DynFlags.PackageFlag’
    In the expression:
      DynFlags.ExposePackage $ "Cabal-" ++ showVersion version
    In the ‘GHC.packageFlags’ field of a record
    In the second argument of ‘($)’, namely
      ‘dflags
         {GHC.ghcLink = GHC.LinkInMemory,
          GHC.hscTarget = GHC.HscInterpreted,
          GHC.packageFlags = [DynFlags.ExposePackage
                              $ "Cabal-" ++ showVersion version],
          GHC.ctxtStkDepth = 1000}’

src/Distribution/Client/Dynamic/Query.hs:190:61:
    Couldn't match expected type ‘DynFlags.PackageArg’
                with actual type ‘[Char]’
    In the second argument of ‘($)’, namely
      ‘"Cabal-" ++ showVersion version’
    In the expression:
      DynFlags.ExposePackage $ "Cabal-" ++ showVersion version
    In the ‘GHC.packageFlags’ field of a record
cabal: Error: some packages failed to install:
dynamic-cabal-0.3.4 failed during the building phase. The exception was:
ExitFailure 1

**Comment by bennofs** [comment]
This should be fixed in master. I'll release 0.3.5 which fixes this issue as soon as the travis build completes.
